//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverInstall.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriverInstall.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding Touchmote Test Certificate to trusted root..
        /// </summary>
        internal static string AddingCertMsg {
            get {
                return ResourceManager.GetString("AddingCertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver installation successfull.
        /// </summary>
        internal static string DriverInstallSuccesfull {
            get {
                return ResourceManager.GetString("DriverInstallSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Touchmote Enhanced Driver Installation.
        /// </summary>
        internal static string DriverInstallTitle {
            get {
                return ResourceManager.GetString("DriverInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver uninstallation successfull.
        /// </summary>
        internal static string DriverUninstallSuccessfull {
            get {
                return ResourceManager.GetString("DriverUninstallSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error disabling driver. {0}.
        /// </summary>
        internal static string ErrorDisablingDriver {
            get {
                return ResourceManager.GetString("ErrorDisablingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error during vmulti driver installation: {0}.
        /// </summary>
        internal static string ErrorVmultiInstall {
            get {
                return ResourceManager.GetString("ErrorVmultiInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error during vmulti driver uninstallation: {0}.
        /// </summary>
        internal static string ErrorVmultiUninstall {
            get {
                return ResourceManager.GetString("ErrorVmultiUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Install.
        /// </summary>
        internal static string InstallButton {
            get {
                return ResourceManager.GetString("InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing Test Touchmote Certificate.
        /// </summary>
        internal static string RemovingCertMsg {
            get {
                return ResourceManager.GetString("RemovingCertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uninstall.
        /// </summary>
        internal static string UninstallButton {
            get {
                return ResourceManager.GetString("UninstallButton", resourceCulture);
            }
        }
    }
}
