//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiiTUIO.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiiTUIO.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  2IR: Bottom.
        /// </summary>
        internal static string _2IRBottom {
            get {
                return ResourceManager.GetString("2IRBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  2IR: Centered.
        /// </summary>
        internal static string _2IRCentered {
            get {
                return ResourceManager.GetString("2IRCentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  2IR: Top.
        /// </summary>
        internal static string _2IRTop {
            get {
                return ResourceManager.GetString("2IRTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  4IR: Diamond.
        /// </summary>
        internal static string _4IRDiamond {
            get {
                return ResourceManager.GetString("4IRDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  4IR: Square.
        /// </summary>
        internal static string _4IRSquare {
            get {
                return ResourceManager.GetString("4IRSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Configuration.
        /// </summary>
        internal static string AdvConfigTitle {
            get {
                return ResourceManager.GetString("AdvConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aim at the BOTTOM center target and press A or B to calibrate..
        /// </summary>
        internal static string AimButtomCenter {
            get {
                return ResourceManager.GetString("AimButtomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Point to the LOWER RIGHT corner and press A or B to calibrate..
        /// </summary>
        internal static string AimButtomRight {
            get {
                return ResourceManager.GetString("AimButtomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Aim at the CENTRAL target and press A or B to calibrate..
        /// </summary>
        internal static string AimCenter {
            get {
                return ResourceManager.GetString("AimCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aim Configuration.
        /// </summary>
        internal static string AimConfig {
            get {
                return ResourceManager.GetString("AimConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press A to confirm calibration, press B to reset calibration.
        /// </summary>
        internal static string AimConfirm {
            get {
                return ResourceManager.GetString("AimConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aim at the LEFT center target and press A or B to calibrate..
        /// </summary>
        internal static string AimLeftCenter {
            get {
                return ResourceManager.GetString("AimLeftCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aim at the RIGHT center target and press A or B to calibrate..
        /// </summary>
        internal static string AimRightCenter {
            get {
                return ResourceManager.GetString("AimRightCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  aim at targets and press A or B to calibrate.
        /// </summary>
        internal static string AimTargets {
            get {
                return ResourceManager.GetString("AimTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aim at the TOP center target and press A or B to calibrate..
        /// </summary>
        internal static string AimTopCenter {
            get {
                return ResourceManager.GetString("AimTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Point to the TOP LEFT corner and press A or B to calibrate..
        /// </summary>
        internal static string AimTopLeft {
            get {
                return ResourceManager.GetString("AimTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Link to application.
        /// </summary>
        internal static string AppLink {
            get {
                return ResourceManager.GetString("AppLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GunMote Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have changed IR arrangement, it is necessary to restart GunMote. Do you want to restart now?.
        /// </summary>
        internal static string Arrangement_RestartConfirmation_Message {
            get {
                return ResourceManager.GetString("Arrangement_RestartConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart Application.
        /// </summary>
        internal static string Arrangement_RestartConfirmation_Title {
            get {
                return ResourceManager.GetString("Arrangement_RestartConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto Disconnect Timeout (ms):.
        /// </summary>
        internal static string AutoDisconnectTimeout {
            get {
                return ResourceManager.GetString("AutoDisconnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Battery: .
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        internal static string btnAll {
            get {
                return ResourceManager.GetString("btnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calibration Margin X:.
        /// </summary>
        internal static string CalibrationMarginX {
            get {
                return ResourceManager.GetString("CalibrationMarginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calibration Margin Y:.
        /// </summary>
        internal static string CalibrationMarginY {
            get {
                return ResourceManager.GetString("CalibrationMarginY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xbox 360 Gamepad.
        /// </summary>
        internal static string cbi360 {
            get {
                return ResourceManager.GetString("cbi360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        internal static string cbiAll {
            get {
                return ResourceManager.GetString("cbiAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursor.
        /// </summary>
        internal static string cbiCursor {
            get {
                return ResourceManager.GetString("cbiCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyboard.
        /// </summary>
        internal static string cbiKeyboard {
            get {
                return ResourceManager.GetString("cbiKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse.
        /// </summary>
        internal static string cbiMouse {
            get {
                return ResourceManager.GetString("cbiMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string cbiOther {
            get {
                return ResourceManager.GetString("cbiOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wiimote.
        /// </summary>
        internal static string cbiWiimote {
            get {
                return ResourceManager.GetString("cbiWiimote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Available in layout selector (hold Home 3 sec).
        /// </summary>
        internal static string cbLayoutChooser {
            get {
                return ResourceManager.GetString("cbLayoutChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string ChangeLanguage_Accept {
            get {
                return ResourceManager.GetString("ChangeLanguage_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string ChangeLanguage_Cancel {
            get {
                return ResourceManager.GetString("ChangeLanguage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose new language.
        /// </summary>
        internal static string ChangeLanguage_Message {
            get {
                return ResourceManager.GetString("ChangeLanguage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        internal static string ChangeLanguage_Title {
            get {
                return ResourceManager.GetString("ChangeLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Layout.
        /// </summary>
        internal static string ChooseLayout {
            get {
                return ResourceManager.GetString("ChooseLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Wiimote Layout .
        /// </summary>
        internal static string ChooseWiimoteLayout {
            get {
                return ResourceManager.GetString("ChooseWiimoteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic Gamepad.
        /// </summary>
        internal static string ClassicGamepad {
            get {
                return ResourceManager.GetString("ClassicGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color ID 1 (R, G, B):.
        /// </summary>
        internal static string ColorID1 {
            get {
                return ResourceManager.GetString("ColorID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color ID 2 (R, G, B):.
        /// </summary>
        internal static string ColorID2 {
            get {
                return ResourceManager.GetString("ColorID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color ID 3 (R, G, B):.
        /// </summary>
        internal static string ColorID3 {
            get {
                return ResourceManager.GetString("ColorID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color ID 4 (R, G, B):.
        /// </summary>
        internal static string ColorID4 {
            get {
                return ResourceManager.GetString("ColorID4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keymaps Config:.
        /// </summary>
        internal static string Configuración_de_Keymaps_ {
            get {
                return ResourceManager.GetString("Configuración de Keymaps:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 Connected Wiimotes.
        /// </summary>
        internal static string connectedCount {
            get {
                return ResourceManager.GetString("connectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect on start.
        /// </summary>
        internal static string ConnectOnStart {
            get {
                return ResourceManager.GetString("ConnectOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Continous Deadzone:.
        /// </summary>
        internal static string DefaultContinousDeadzone {
            get {
                return ResourceManager.GetString("DefaultContinousDeadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Continous Press Threshold:.
        /// </summary>
        internal static string DefaultContinousPressThreshold {
            get {
                return ResourceManager.GetString("DefaultContinousPressThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Continous Scale:.
        /// </summary>
        internal static string DefaultContinousScale {
            get {
                return ResourceManager.GetString("DefaultContinousScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disconnect all wiimotes on exit.
        /// </summary>
        internal static string DisconnectOnExit {
            get {
                return ResourceManager.GetString("DisconnectOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disconnect Wiimotes On Dolphin.
        /// </summary>
        internal static string DisconnectWiimotesOnDolphin {
            get {
                return ResourceManager.GetString("DisconnectWiimotesOnDolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Dolphin Folder.
        /// </summary>
        internal static string DolphinFolder {
            get {
                return ResourceManager.GetString("DolphinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dolphin Path:.
        /// </summary>
        internal static string DolphinPath {
            get {
                return ResourceManager.GetString("DolphinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scale.
        /// </summary>
        internal static string dScale {
            get {
                return ResourceManager.GetString("dScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Threshold.
        /// </summary>
        internal static string dThreshold {
            get {
                return ResourceManager.GetString("dThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wiimote configuration.
        /// </summary>
        internal static string EditKeymaps {
            get {
                return ResourceManager.GetString("EditKeymaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Layout.
        /// </summary>
        internal static string EditLayout {
            get {
                return ResourceManager.GetString("EditLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error_Title_Generic {
            get {
                return ResourceManager.GetString("Error_Title_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FPS Mouse Deadzone:.
        /// </summary>
        internal static string FpsmouseDeadzone {
            get {
                return ResourceManager.GetString("FpsmouseDeadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FPS Mouse Speed:.
        /// </summary>
        internal static string FpsmouseSpeed {
            get {
                return ResourceManager.GetString("FpsmouseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Gamepads.
        /// </summary>
        internal static string GamepadsLabel {
            get {
                return ResourceManager.GetString("GamepadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Configuration.
        /// </summary>
        internal static string GlobalConf {
            get {
                return ResourceManager.GetString("GlobalConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hold Down.
        /// </summary>
        internal static string HoldDown {
            get {
                return ResourceManager.GetString("HoldDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wiimote IDs Color Configuration.
        /// </summary>
        internal static string IDTitle {
            get {
                return ResourceManager.GetString("IDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  aim at the targets and press A or B to calibrate..
        /// </summary>
        internal static string insText2 {
            get {
                return ResourceManager.GetString("insText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keymap Configuration.
        /// </summary>
        internal static string KeymapConfigTitle {
            get {
                return ResourceManager.GetString("KeymapConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string KeyMapDel {
            get {
                return ResourceManager.GetString("KeyMapDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout.
        /// </summary>
        internal static string KeyMapLayout {
            get {
                return ResourceManager.GetString("KeyMapLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keymaps Config File:.
        /// </summary>
        internal static string KeymapsConfig {
            get {
                return ResourceManager.GetString("KeymapsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Keymaps Configuration File.
        /// </summary>
        internal static string KeymapsConfigSelect {
            get {
                return ResourceManager.GetString("KeymapsConfigSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Keymaps Folder.
        /// </summary>
        internal static string KeymapsFolder {
            get {
                return ResourceManager.GetString("KeymapsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keymaps Path:.
        /// </summary>
        internal static string KeymapsPath {
            get {
                return ResourceManager.GetString("KeymapsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout changed to.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize on start.
        /// </summary>
        internal static string MinimizeOnStart {
            get {
                return ResourceManager.GetString("MinimizeOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize to tray.
        /// </summary>
        internal static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No sensors are found. Make sure you are at the right distance and pointing at the screen..
        /// </summary>
        internal static string NoSensors {
            get {
                return ResourceManager.GetString("NoSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications Enabled.
        /// </summary>
        internal static string NotificationsEnabled {
            get {
                return ResourceManager.GetString("NotificationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do not keep the window always on top.
        /// </summary>
        internal static string NoTopmost {
            get {
                return ResourceManager.GetString("NoTopmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One Wiimote connected.
        /// </summary>
        internal static string OneWiimoteConnected {
            get {
                return ResourceManager.GetString("OneWiimoteConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outputs.
        /// </summary>
        internal static string OutputsLabel {
            get {
                return ResourceManager.GetString("OutputsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pair on Start.
        /// </summary>
        internal static string pairOnStart {
            get {
                return ResourceManager.GetString("pairOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pairing....
        /// </summary>
        internal static string pairWiimote {
            get {
                return ResourceManager.GetString("pairWiimote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pair Wiimotes.
        /// </summary>
        internal static string PairWiimotes {
            get {
                return ResourceManager.GetString("PairWiimotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Configuration.
        /// </summary>
        internal static string PointerConfigHeaderText {
            get {
                return ResourceManager.GetString("PointerConfigHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Cursor Size:.
        /// </summary>
        internal static string PointerCursorSize {
            get {
                return ResourceManager.GetString("PointerCursorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer FPS:.
        /// </summary>
        internal static string PointerFPS {
            get {
                return ResourceManager.GetString("PointerFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Margins Left/Right:.
        /// </summary>
        internal static string PointerMarginsLeftRight {
            get {
                return ResourceManager.GetString("PointerMarginsLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Margins Top/Bottom:.
        /// </summary>
        internal static string PointerMarginsTopBottom {
            get {
                return ResourceManager.GetString("PointerMarginsTopBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Position Radius:.
        /// </summary>
        internal static string PointerPositionRadius {
            get {
                return ResourceManager.GetString("PointerPositionRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer Position Smoothing:.
        /// </summary>
        internal static string PointerPositionSmoothing {
            get {
                return ResourceManager.GetString("PointerPositionSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer SensorBar Position Compensation:.
        /// </summary>
        internal static string PointerSensorBarPosCompensation {
            get {
                return ResourceManager.GetString("PointerSensorBarPosCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press SYNC.
        /// </summary>
        internal static string PressSyncPart1 {
            get {
                return ResourceManager.GetString("PressSyncPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  for permanent connection or 1+2 for temporary connection..
        /// </summary>
        internal static string PressSyncPart2 {
            get {
                return ResourceManager.GetString("PressSyncPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primary Monitor:.
        /// </summary>
        internal static string PrimaryMonitor {
            get {
                return ResourceManager.GetString("PrimaryMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active Profile:.
        /// </summary>
        internal static string Profile_ActiveProfile {
            get {
                return ResourceManager.GetString("Profile_ActiveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calibration Profiles.
        /// </summary>
        internal static string Profile_CalibrationProfiles {
            get {
                return ResourceManager.GetString("Profile_CalibrationProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot delete the &apos;Default Profile&apos; profile..
        /// </summary>
        internal static string Profile_CannotDeleteDefault {
            get {
                return ResourceManager.GetString("Profile_CannotDeleteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the profile &apos;{0}&apos;? This action is irreversible..
        /// </summary>
        internal static string Profile_ConfirmDeletion_Message {
            get {
                return ResourceManager.GetString("Profile_ConfirmDeletion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Deletion.
        /// </summary>
        internal static string Profile_ConfirmDeletion_Title {
            get {
                return ResourceManager.GetString("Profile_ConfirmDeletion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Profile.
        /// </summary>
        internal static string Profile_CreateButton {
            get {
                return ResourceManager.GetString("Profile_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile &apos;{0}&apos; created and activated..
        /// </summary>
        internal static string Profile_CreatedAndActivated {
            get {
                return ResourceManager.GetString("Profile_CreatedAndActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while creating the profile: {0}.
        /// </summary>
        internal static string Profile_CreateError_Message {
            get {
                return ResourceManager.GetString("Profile_CreateError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Creating Profile.
        /// </summary>
        internal static string Profile_CreateError_Title {
            get {
                return ResourceManager.GetString("Profile_CreateError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Profile.
        /// </summary>
        internal static string Profile_DeleteButton {
            get {
                return ResourceManager.GetString("Profile_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile &apos;{0}&apos; deleted..
        /// </summary>
        internal static string Profile_Deleted {
            get {
                return ResourceManager.GetString("Profile_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while deleting the profile: {0}.
        /// </summary>
        internal static string Profile_DeleteError_Message {
            get {
                return ResourceManager.GetString("Profile_DeleteError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Deleting Profile.
        /// </summary>
        internal static string Profile_DeleteError_Title {
            get {
                return ResourceManager.GetString("Profile_DeleteError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The profile &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Profile_DoesNotExist {
            get {
                return ResourceManager.GetString("Profile_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a name for the new profile..
        /// </summary>
        internal static string Profile_EnterName {
            get {
                return ResourceManager.GetString("Profile_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The profile &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Profile_Exists {
            get {
                return ResourceManager.GetString("Profile_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile name cannot be empty..
        /// </summary>
        internal static string Profile_NameEmpty {
            get {
                return ResourceManager.GetString("Profile_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Profile:.
        /// </summary>
        internal static string Profile_NewProfile {
            get {
                return ResourceManager.GetString("Profile_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a profile to delete..
        /// </summary>
        internal static string Profile_SelectToDelete {
            get {
                return ResourceManager.GetString("Profile_SelectToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Off Screen.
        /// </summary>
        internal static string rbOffscreen {
            get {
                return ResourceManager.GetString("rbOffscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  On Screen.
        /// </summary>
        internal static string rbOnscreen {
            get {
                return ResourceManager.GetString("rbOnscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Release.
        /// </summary>
        internal static string ReleaseText {
            get {
                return ResourceManager.GetString("ReleaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language has been changed. The application will restart to apply the changes..
        /// </summary>
        internal static string Restart_Message {
            get {
                return ResourceManager.GetString("Restart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart Required.
        /// </summary>
        internal static string Restart_Title {
            get {
                return ResourceManager.GetString("Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error restarting the application: {0}.
        /// </summary>
        internal static string RestartError {
            get {
                return ResourceManager.GetString("RestartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XInput Rumble Configuration.
        /// </summary>
        internal static string RumbleXinputTitle {
            get {
                return ResourceManager.GetString("RumbleXinputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save and Restart GunMote.
        /// </summary>
        internal static string SaveAndReboot {
            get {
                return ResourceManager.GetString("SaveAndReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not save calibration settings. Please check file permissions or restart the application..
        /// </summary>
        internal static string SaveError_Message {
            get {
                return ResourceManager.GetString("SaveError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Error.
        /// </summary>
        internal static string SaveError_Title {
            get {
                return ResourceManager.GetString("SaveError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor Mode.
        /// </summary>
        internal static string SensorMode {
            get {
                return ResourceManager.GetString("SensorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string SettingsBut {
            get {
                return ResourceManager.GetString("SettingsBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake Count:.
        /// </summary>
        internal static string ShakeCount {
            get {
                return ResourceManager.GetString("ShakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake Max Time In Between (ms):.
        /// </summary>
        internal static string ShakeMaxTimeInBetween {
            get {
                return ResourceManager.GetString("ShakeMaxTimeInBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake Pressed Time (ms):.
        /// </summary>
        internal static string ShakePressedTime {
            get {
                return ResourceManager.GetString("ShakePressedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake Threshold:.
        /// </summary>
        internal static string ShakeThreshold {
            get {
                return ResourceManager.GetString("ShakeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake Configuration.
        /// </summary>
        internal static string ShakeTitle {
            get {
                return ResourceManager.GetString("ShakeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wiimote  Sound and Rumble Configuration.
        /// </summary>
        internal static string SoundAndRumbleTitle {
            get {
                return ResourceManager.GetString("SoundAndRumbleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string Success_Title {
            get {
                return ResourceManager.GetString("Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add (+).
        /// </summary>
        internal static string tAdd {
            get {
                return ResourceManager.GetString("tAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string tBack {
            get {
                return ResourceManager.GetString("tBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string tbDefault {
            get {
                return ResourceManager.GetString("tbDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string tbKeymapTitle {
            get {
                return ResourceManager.GetString("tbKeymapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string tbName {
            get {
                return ResourceManager.GetString("tbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Output Filter.
        /// </summary>
        internal static string tbOutputFilter {
            get {
                return ResourceManager.GetString("tbOutputFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Back.
        /// </summary>
        internal static string tBrowserBack {
            get {
                return ResourceManager.GetString("tBrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Favorites.
        /// </summary>
        internal static string tBrowserFavorites {
            get {
                return ResourceManager.GetString("tBrowserFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Forward.
        /// </summary>
        internal static string tBrowserForward {
            get {
                return ResourceManager.GetString("tBrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Home.
        /// </summary>
        internal static string tBrowserHome {
            get {
                return ResourceManager.GetString("tBrowserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Refresh.
        /// </summary>
        internal static string tBrowserRefresh {
            get {
                return ResourceManager.GetString("tBrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Search.
        /// </summary>
        internal static string tBrowserSearch {
            get {
                return ResourceManager.GetString("tBrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Stop.
        /// </summary>
        internal static string tBrowserStop {
            get {
                return ResourceManager.GetString("tBrowserStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Bumper.
        /// </summary>
        internal static string tBumperL {
            get {
                return ResourceManager.GetString("tBumperL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Bumper.
        /// </summary>
        internal static string tBumperR {
            get {
                return ResourceManager.GetString("tBumperR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caps Lock.
        /// </summary>
        internal static string tCapsLock {
            get {
                return ResourceManager.GetString("tCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing....
        /// </summary>
        internal static string TClosing {
            get {
                return ResourceManager.GetString("TClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comma (,).
        /// </summary>
        internal static string tComma {
            get {
                return ResourceManager.GetString("tComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal (.).
        /// </summary>
        internal static string tDecimal {
            get {
                return ResourceManager.GetString("tDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string tDel {
            get {
                return ResourceManager.GetString("tDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        internal static string tDisableKey {
            get {
                return ResourceManager.GetString("tDisableKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divide (/).
        /// </summary>
        internal static string tDivide {
            get {
                return ResourceManager.GetString("tDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Down.
        /// </summary>
        internal static string tDown {
            get {
                return ResourceManager.GetString("tDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        internal static string tEnd {
            get {
                return ResourceManager.GetString("tEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Configuration.
        /// </summary>
        internal static string TestConfigHeader {
            get {
                return ResourceManager.GetString("TestConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enables Test Delta Acceleration:.
        /// </summary>
        internal static string TestDeltaAccel {
            get {
                return ResourceManager.GetString("TestDeltaAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test delta acceleration smoothing duration:.
        /// </summary>
        internal static string TestDeltaAccelEasingDuration {
            get {
                return ResourceManager.GetString("TestDeltaAccelEasingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Delta Acceleration Maximun Travel:.
        /// </summary>
        internal static string TestDeltaAccelMaxTravel {
            get {
                return ResourceManager.GetString("TestDeltaAccelMaxTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Delta Acceleration Minimun Travel:.
        /// </summary>
        internal static string TestDeltaAccelMinTravel {
            get {
                return ResourceManager.GetString("TestDeltaAccelMinTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Delta Acceleration Multiplier:.
        /// </summary>
        internal static string TestDeltaAccelMulti {
            get {
                return ResourceManager.GetString("TestDeltaAccelMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Fps mouse Offset:.
        /// </summary>
        internal static string TestFpsmouseOffset {
            get {
                return ResourceManager.GetString("TestFpsmouseOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enables Test Lightgun Oneeuro Beta:.
        /// </summary>
        internal static string TestLightgunOneeuroBeta {
            get {
                return ResourceManager.GetString("TestLightgunOneeuroBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Lightgun Oneeuro Minimun cut off:.
        /// </summary>
        internal static string TestLightgunOneeuroMincutoff {
            get {
                return ResourceManager.GetString("TestLightgunOneeuroMincutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test region X easing duration:.
        /// </summary>
        internal static string TestRegionEasingXDuration {
            get {
                return ResourceManager.GetString("TestRegionEasingXDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test region X easing offset:.
        /// </summary>
        internal static string TestRegionEasingXOffset {
            get {
                return ResourceManager.GetString("TestRegionEasingXOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Smoothing Weight:.
        /// </summary>
        internal static string TestSmoothingWeight {
            get {
                return ResourceManager.GetString("TestSmoothingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extension.
        /// </summary>
        internal static string tExtension {
            get {
                return ResourceManager.GetString("tExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FPS Mouse.
        /// </summary>
        internal static string tFPSMouse {
            get {
                return ResourceManager.GetString("tFPSMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guide.
        /// </summary>
        internal static string tGuide {
            get {
                return ResourceManager.GetString("tGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  this page.
        /// </summary>
        internal static string ThisPage {
            get {
                return ResourceManager.GetString("ThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string tHome {
            get {
                return ResourceManager.GetString("tHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string tInsert {
            get {
                return ResourceManager.GetString("tInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Trigger Push.
        /// </summary>
        internal static string tL {
            get {
                return ResourceManager.GetString("tL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Alt.
        /// </summary>
        internal static string tLAlt {
            get {
                return ResourceManager.GetString("tLAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Control.
        /// </summary>
        internal static string tLControl {
            get {
                return ResourceManager.GetString("tLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left.
        /// </summary>
        internal static string tLeft {
            get {
                return ResourceManager.GetString("tLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lightgun Mouse.
        /// </summary>
        internal static string tLightgunMouse {
            get {
                return ResourceManager.GetString("tLightgunMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Long Rumble.
        /// </summary>
        internal static string tLongRumble {
            get {
                return ResourceManager.GetString("tLongRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Shift.
        /// </summary>
        internal static string tLShift {
            get {
                return ResourceManager.GetString("tLShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Win.
        /// </summary>
        internal static string tLWin {
            get {
                return ResourceManager.GetString("tLWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minus (-).
        /// </summary>
        internal static string tMinus {
            get {
                return ResourceManager.GetString("tMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse.
        /// </summary>
        internal static string tMouse {
            get {
                return ResourceManager.GetString("tMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Move Down.
        /// </summary>
        internal static string tMouseDown {
            get {
                return ResourceManager.GetString("tMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Extra Button 1.
        /// </summary>
        internal static string tMouseExtra1 {
            get {
                return ResourceManager.GetString("tMouseExtra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Extra Button 2.
        /// </summary>
        internal static string tMouseExtra2 {
            get {
                return ResourceManager.GetString("tMouseExtra2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Move Left.
        /// </summary>
        internal static string tMouseLeft {
            get {
                return ResourceManager.GetString("tMouseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Left Button.
        /// </summary>
        internal static string tMouseLeftB {
            get {
                return ResourceManager.GetString("tMouseLeftB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Middle Button.
        /// </summary>
        internal static string tMouseMiddleB {
            get {
                return ResourceManager.GetString("tMouseMiddleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Move Right.
        /// </summary>
        internal static string tMouseRight {
            get {
                return ResourceManager.GetString("tMouseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Right Button.
        /// </summary>
        internal static string tMouseRightB {
            get {
                return ResourceManager.GetString("tMouseRightB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Move Up.
        /// </summary>
        internal static string tMouseUp {
            get {
                return ResourceManager.GetString("tMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Wheel Down.
        /// </summary>
        internal static string tMouseWheelDown {
            get {
                return ResourceManager.GetString("tMouseWheelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Wheel Up.
        /// </summary>
        internal static string tMouseWheelUp {
            get {
                return ResourceManager.GetString("tMouseWheelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiply (*).
        /// </summary>
        internal static string tMultiply {
            get {
                return ResourceManager.GetString("tMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next Track.
        /// </summary>
        internal static string tNextTrack {
            get {
                return ResourceManager.GetString("tNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad Down.
        /// </summary>
        internal static string tNumDown {
            get {
                return ResourceManager.GetString("tNumDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad Left.
        /// </summary>
        internal static string tNumLeft {
            get {
                return ResourceManager.GetString("tNumLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numlock.
        /// </summary>
        internal static string tNumlock {
            get {
                return ResourceManager.GetString("tNumlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad Right.
        /// </summary>
        internal static string tNumRight {
            get {
                return ResourceManager.GetString("tNumRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad Up.
        /// </summary>
        internal static string tNumUp {
            get {
                return ResourceManager.GetString("tNumUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One (1).
        /// </summary>
        internal static string tOne {
            get {
                return ResourceManager.GetString("tOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GunMote provides a way to act as a single or multiple Wiimotes as a lightgun device and gamepad..
        /// </summary>
        internal static string TouchmoteAbout1 {
            get {
                return ResourceManager.GetString("TouchmoteAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks to Symphax for creating this wonderful application that has given a second life to our Wiimotes, to Ryochan for his improvements and to Suegrini for adding the ability to use 4 IR LEDS for greater accuracy. This version continues that work and adds improvements to the diamond arrangement of the IR LEDs..
        /// </summary>
        internal static string TouchmoteAbout2 {
            get {
                return ResourceManager.GetString("TouchmoteAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page Down.
        /// </summary>
        internal static string tPagDown {
            get {
                return ResourceManager.GetString("tPagDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page Up.
        /// </summary>
        internal static string tPagUp {
            get {
                return ResourceManager.GetString("tPagUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string tPause {
            get {
                return ResourceManager.GetString("tPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Period (.).
        /// </summary>
        internal static string tPeriod {
            get {
                return ResourceManager.GetString("tPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play/Pause.
        /// </summary>
        internal static string tPlayPause {
            get {
                return ResourceManager.GetString("tPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plus (+).
        /// </summary>
        internal static string tPlus {
            get {
                return ResourceManager.GetString("tPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pointer.
        /// </summary>
        internal static string tPointer {
            get {
                return ResourceManager.GetString("tPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Pointer.
        /// </summary>
        internal static string tPointerXminus {
            get {
                return ResourceManager.GetString("tPointerXminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Pointer.
        /// </summary>
        internal static string tPointerXplus {
            get {
                return ResourceManager.GetString("tPointerXplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Up Pointer.
        /// </summary>
        internal static string tPointerYminus {
            get {
                return ResourceManager.GetString("tPointerYminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Down Pointer.
        /// </summary>
        internal static string tPointerYplus {
            get {
                return ResourceManager.GetString("tPointerYplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursor Press.
        /// </summary>
        internal static string tPressCursor {
            get {
                return ResourceManager.GetString("tPressCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous Track.
        /// </summary>
        internal static string tPrevTrack {
            get {
                return ResourceManager.GetString("tPrevTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print Screen.
        /// </summary>
        internal static string tPrintScreen {
            get {
                return ResourceManager.GetString("tPrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Trigger Push.
        /// </summary>
        internal static string tR {
            get {
                return ResourceManager.GetString("tR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Alt.
        /// </summary>
        internal static string tRAlt {
            get {
                return ResourceManager.GetString("tRAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press to edit GunMote parameters.
        /// </summary>
        internal static string TrayBalloonTip {
            get {
                return ResourceManager.GetString("TrayBalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Control.
        /// </summary>
        internal static string tRControl {
            get {
                return ResourceManager.GetString("tRControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right.
        /// </summary>
        internal static string tRight {
            get {
                return ResourceManager.GetString("tRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Shift.
        /// </summary>
        internal static string tRShift {
            get {
                return ResourceManager.GetString("tRShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rumble Alternance.
        /// </summary>
        internal static string tRumbleAlt {
            get {
                return ResourceManager.GetString("tRumbleAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rumble Hold.
        /// </summary>
        internal static string tRumbleHold {
            get {
                return ResourceManager.GetString("tRumbleHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Win.
        /// </summary>
        internal static string tRWin {
            get {
                return ResourceManager.GetString("tRWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try again buddy.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake.
        /// </summary>
        internal static string tShake {
            get {
                return ResourceManager.GetString("tShake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift.
        /// </summary>
        internal static string tShift {
            get {
                return ResourceManager.GetString("tShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Short Rumble.
        /// </summary>
        internal static string tShortRumble {
            get {
                return ResourceManager.GetString("tShortRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound 1.
        /// </summary>
        internal static string tSound1 {
            get {
                return ResourceManager.GetString("tSound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound 2.
        /// </summary>
        internal static string tSound2 {
            get {
                return ResourceManager.GetString("tSound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Loop.
        /// </summary>
        internal static string tSoundLoop {
            get {
                return ResourceManager.GetString("tSoundLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Space.
        /// </summary>
        internal static string tSpace {
            get {
                return ResourceManager.GetString("tSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string tStart {
            get {
                return ResourceManager.GetString("tStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stick Down.
        /// </summary>
        internal static string tStickDown {
            get {
                return ResourceManager.GetString("tStickDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Center.
        /// </summary>
        internal static string tStickLCenter {
            get {
                return ResourceManager.GetString("tStickLCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Down.
        /// </summary>
        internal static string tStickLDown {
            get {
                return ResourceManager.GetString("tStickLDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick .
        /// </summary>
        internal static string tStickLeft {
            get {
                return ResourceManager.GetString("tStickLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Left.
        /// </summary>
        internal static string tStickLLeft {
            get {
                return ResourceManager.GetString("tStickLLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Lightgun.
        /// </summary>
        internal static string tStickLLight {
            get {
                return ResourceManager.GetString("tStickLLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Lightgun 4:3.
        /// </summary>
        internal static string tStickLLight43 {
            get {
                return ResourceManager.GetString("tStickLLight43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Press.
        /// </summary>
        internal static string tStickLPress {
            get {
                return ResourceManager.GetString("tStickLPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Right.
        /// </summary>
        internal static string tStickLRight {
            get {
                return ResourceManager.GetString("tStickLRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Stick Up.
        /// </summary>
        internal static string tStickLUp {
            get {
                return ResourceManager.GetString("tStickLUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Center.
        /// </summary>
        internal static string tStickRCenter {
            get {
                return ResourceManager.GetString("tStickRCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Down.
        /// </summary>
        internal static string tStickRDown {
            get {
                return ResourceManager.GetString("tStickRDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick .
        /// </summary>
        internal static string tStickRight {
            get {
                return ResourceManager.GetString("tStickRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Left.
        /// </summary>
        internal static string tStickRLeft {
            get {
                return ResourceManager.GetString("tStickRLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Lightgun.
        /// </summary>
        internal static string tStickRLight {
            get {
                return ResourceManager.GetString("tStickRLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Lightgun 4:3.
        /// </summary>
        internal static string tStickRLight43 {
            get {
                return ResourceManager.GetString("tStickRLight43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stick Rotation(-).
        /// </summary>
        internal static string tStickRotationMinus {
            get {
                return ResourceManager.GetString("tStickRotationMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stick Rotation(+).
        /// </summary>
        internal static string tStickRotationPlus {
            get {
                return ResourceManager.GetString("tStickRotationPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Press.
        /// </summary>
        internal static string tStickRPress {
            get {
                return ResourceManager.GetString("tStickRPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Right.
        /// </summary>
        internal static string tStickRRight {
            get {
                return ResourceManager.GetString("tStickRRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Stick Up.
        /// </summary>
        internal static string tStickRUp {
            get {
                return ResourceManager.GetString("tStickRUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stick Up.
        /// </summary>
        internal static string tStickUp {
            get {
                return ResourceManager.GetString("tStickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        internal static string tStop {
            get {
                return ResourceManager.GetString("tStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtract (-).
        /// </summary>
        internal static string tSubtract {
            get {
                return ResourceManager.GetString("tSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt X -.
        /// </summary>
        internal static string tTiltXMinus {
            get {
                return ResourceManager.GetString("tTiltXMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt X +.
        /// </summary>
        internal static string tTiltXPlus {
            get {
                return ResourceManager.GetString("tTiltXPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt Y -.
        /// </summary>
        internal static string tTiltYMinus {
            get {
                return ResourceManager.GetString("tTiltYMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt Y +.
        /// </summary>
        internal static string tTiltYPlus {
            get {
                return ResourceManager.GetString("tTiltYPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt Z -.
        /// </summary>
        internal static string tTiltZMinus {
            get {
                return ResourceManager.GetString("tTiltZMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tilt Z +.
        /// </summary>
        internal static string tTiltZPlus {
            get {
                return ResourceManager.GetString("tTiltZPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Trigger.
        /// </summary>
        internal static string tTriggerL {
            get {
                return ResourceManager.GetString("tTriggerL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Trigger.
        /// </summary>
        internal static string tTriggerR {
            get {
                return ResourceManager.GetString("tTriggerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Two (1).
        /// </summary>
        internal static string tTwo {
            get {
                return ResourceManager.GetString("tTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Up.
        /// </summary>
        internal static string tUp {
            get {
                return ResourceManager.GetString("tUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Down.
        /// </summary>
        internal static string tVolumeDown {
            get {
                return ResourceManager.GetString("tVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Mute.
        /// </summary>
        internal static string tVolumeMute {
            get {
                return ResourceManager.GetString("tVolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Up.
        /// </summary>
        internal static string tVolumeUp {
            get {
                return ResourceManager.GetString("tVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GitHub API error ({0}): {1}.
        /// </summary>
        internal static string UpdateCheck_ApiError {
            get {
                return ResourceManager.GetString("UpdateCheck_ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The update has been downloaded. Press &apos;Yes&apos; to close GunMote and continue with the installation, or &apos;Cancel&apos; if you do not wish to update..
        /// </summary>
        internal static string UpdateCheck_ConfirmInstallationMessage {
            get {
                return ResourceManager.GetString("UpdateCheck_ConfirmInstallationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Installation.
        /// </summary>
        internal static string UpdateCheck_ConfirmInstallationTitle {
            get {
                return ResourceManager.GetString("UpdateCheck_ConfirmInstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error when checking for updates: {0}.
        /// </summary>
        internal static string UpdateCheck_ConnectionError {
            get {
                return ResourceManager.GetString("UpdateCheck_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updater download cancelled..
        /// </summary>
        internal static string UpdateCheck_DownloadCancelled {
            get {
                return ResourceManager.GetString("UpdateCheck_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download complete at: {0}.
        /// </summary>
        internal static string UpdateCheck_DownloadComplete {
            get {
                return ResourceManager.GetString("UpdateCheck_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error downloading updater: {0}.
        /// </summary>
        internal static string UpdateCheck_DownloadError {
            get {
                return ResourceManager.GetString("UpdateCheck_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading updater: {0}.
        /// </summary>
        internal static string UpdateCheck_DownloadingUpdate {
            get {
                return ResourceManager.GetString("UpdateCheck_DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error when starting the update check: {0}.
        /// </summary>
        internal static string UpdateCheck_InitialCheckError {
            get {
                return ResourceManager.GetString("UpdateCheck_InitialCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update installation cancelled by user..
        /// </summary>
        internal static string UpdateCheck_InstallationCancelled {
            get {
                return ResourceManager.GetString("UpdateCheck_InstallationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error launching installer: {0}.
        /// </summary>
        internal static string UpdateCheck_InstallationError {
            get {
                return ResourceManager.GetString("UpdateCheck_InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading JSON response from GitHub: {0}.
        /// </summary>
        internal static string UpdateCheck_JsonError {
            get {
                return ResourceManager.GetString("UpdateCheck_JsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are using the latest version available..
        /// </summary>
        internal static string UpdateCheck_LatestVersion {
            get {
                return ResourceManager.GetString("UpdateCheck_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new version ({0}) is available, do you want to download and install it?.
        /// </summary>
        internal static string UpdateCheck_NewVersionAvailable_Message {
            get {
                return ResourceManager.GetString("UpdateCheck_NewVersionAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Available.
        /// </summary>
        internal static string UpdateCheck_NewVersionAvailable_Title {
            get {
                return ResourceManager.GetString("UpdateCheck_NewVersionAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No installer found in the latest GitHub release..
        /// </summary>
        internal static string UpdateCheck_NoInstallerFound {
            get {
                return ResourceManager.GetString("UpdateCheck_NoInstallerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected error when checking for updates: {0}.
        /// </summary>
        internal static string UpdateCheck_UnexpectedError {
            get {
                return ResourceManager.GetString("UpdateCheck_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loop Sound Time (ms):.
        /// </summary>
        internal static string WiimodeLoopSoundTime {
            get {
                return ResourceManager.GetString("WiimodeLoopSoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wiimode Rumble Time Alternating Off (ms):.
        /// </summary>
        internal static string WiimodeRumbleTimeAlternatingOff {
            get {
                return ResourceManager.GetString("WiimodeRumbleTimeAlternatingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rumble Time Alternating On (ms):.
        /// </summary>
        internal static string WiimodeRumbleTimeAlternatingOn {
            get {
                return ResourceManager.GetString("WiimodeRumbleTimeAlternatingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least one of your Wiimotes is not compatible with the Microsoft Bluetooth stack, use only Wiimotes manufactured before November 2011 or follow the instructions at.
        /// </summary>
        internal static string WiimoteComp {
            get {
                return ResourceManager.GetString("WiimoteComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rumble Time Long (ms):.
        /// </summary>
        internal static string WiimoteRumbleTimeLong {
            get {
                return ResourceManager.GetString("WiimoteRumbleTimeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rumble Time Short (ms):.
        /// </summary>
        internal static string WiimoteRumbleTimeShort {
            get {
                return ResourceManager.GetString("WiimoteRumbleTimeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Wiimotes Connected.
        /// </summary>
        internal static string WiimotesConnected {
            get {
                return ResourceManager.GetString("WiimotesConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start GunMote with Windows.
        /// </summary>
        internal static string WindowsStart {
            get {
                return ResourceManager.GetString("WindowsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xinput Rumble Threshold Big:.
        /// </summary>
        internal static string XinputRumbleThresholdBig {
            get {
                return ResourceManager.GetString("XinputRumbleThresholdBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xinput Rumble Threshold Small:.
        /// </summary>
        internal static string XinputRumbleThresholdSmall {
            get {
                return ResourceManager.GetString("XinputRumbleThresholdSmall", resourceCulture);
            }
        }
    }
}
